# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_serving_client_request_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_serving_client_request_response.proto',
  package='DeepLearningModelServer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+model_serving_client_request_response.proto\x12\x17\x44\x65\x65pLearningModelServer\"\xc6\x01\n\x19ModelServingClientRequest\x12\x0f\n\x07TraceId\x18\x01 \x01(\t\x12\x0f\n\x07IsDebug\x18\x02 \x01(\x08\x12\x41\n\x06\x41\x63tion\x18\x03 \x01(\x0e\x32\x31.DeepLearningModelServer.ModelServingClientAction\x12\x10\n\x08Requests\x18\x04 \x03(\t\x12\x14\n\x0cRequestBlobs\x18\x05 \x03(\x0c\x12\n\n\x02Id\x18\x06 \x01(\x03\x12\x10\n\x08TraceIds\x18\x07 \x03(\t\"\xb3\x01\n\x1aModelServingClientResponse\x12\x45\n\x04\x43ode\x18\x01 \x01(\x0e\x32\x37.DeepLearningModelServer.ModelServingClientResponseCode\x12\x11\n\tResponses\x18\x02 \x03(\t\x12\x15\n\rResponseBlobs\x18\x03 \x03(\x0c\x12\x18\n\x10ModelLatencyInUs\x18\x04 \x01(\r\x12\n\n\x02Id\x18\x06 \x01(\x03*7\n\x1eModelServingClientResponseCode\x12\x0b\n\x07Success\x10\x00\x12\x08\n\x04\x46\x61il\x10\x01*.\n\x18ModelServingClientAction\x12\x08\n\x04Ping\x10\x00\x12\x08\n\x04\x45val\x10\x01\x62\x06proto3')
)

_MODELSERVINGCLIENTRESPONSECODE = _descriptor.EnumDescriptor(
  name='ModelServingClientResponseCode',
  full_name='DeepLearningModelServer.ModelServingClientResponseCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Success', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Fail', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=455,
  serialized_end=510,
)
_sym_db.RegisterEnumDescriptor(_MODELSERVINGCLIENTRESPONSECODE)

ModelServingClientResponseCode = enum_type_wrapper.EnumTypeWrapper(_MODELSERVINGCLIENTRESPONSECODE)
_MODELSERVINGCLIENTACTION = _descriptor.EnumDescriptor(
  name='ModelServingClientAction',
  full_name='DeepLearningModelServer.ModelServingClientAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ping', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Eval', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=512,
  serialized_end=558,
)
_sym_db.RegisterEnumDescriptor(_MODELSERVINGCLIENTACTION)

ModelServingClientAction = enum_type_wrapper.EnumTypeWrapper(_MODELSERVINGCLIENTACTION)
Success = 0
Fail = 1
Ping = 0
Eval = 1



_MODELSERVINGCLIENTREQUEST = _descriptor.Descriptor(
  name='ModelServingClientRequest',
  full_name='DeepLearningModelServer.ModelServingClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TraceId', full_name='DeepLearningModelServer.ModelServingClientRequest.TraceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsDebug', full_name='DeepLearningModelServer.ModelServingClientRequest.IsDebug', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Action', full_name='DeepLearningModelServer.ModelServingClientRequest.Action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Requests', full_name='DeepLearningModelServer.ModelServingClientRequest.Requests', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RequestBlobs', full_name='DeepLearningModelServer.ModelServingClientRequest.RequestBlobs', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Id', full_name='DeepLearningModelServer.ModelServingClientRequest.Id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TraceIds', full_name='DeepLearningModelServer.ModelServingClientRequest.TraceIds', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=271,
)


_MODELSERVINGCLIENTRESPONSE = _descriptor.Descriptor(
  name='ModelServingClientResponse',
  full_name='DeepLearningModelServer.ModelServingClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='DeepLearningModelServer.ModelServingClientResponse.Code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Responses', full_name='DeepLearningModelServer.ModelServingClientResponse.Responses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ResponseBlobs', full_name='DeepLearningModelServer.ModelServingClientResponse.ResponseBlobs', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ModelLatencyInUs', full_name='DeepLearningModelServer.ModelServingClientResponse.ModelLatencyInUs', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Id', full_name='DeepLearningModelServer.ModelServingClientResponse.Id', index=4,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=453,
)

_MODELSERVINGCLIENTREQUEST.fields_by_name['Action'].enum_type = _MODELSERVINGCLIENTACTION
_MODELSERVINGCLIENTRESPONSE.fields_by_name['Code'].enum_type = _MODELSERVINGCLIENTRESPONSECODE
DESCRIPTOR.message_types_by_name['ModelServingClientRequest'] = _MODELSERVINGCLIENTREQUEST
DESCRIPTOR.message_types_by_name['ModelServingClientResponse'] = _MODELSERVINGCLIENTRESPONSE
DESCRIPTOR.enum_types_by_name['ModelServingClientResponseCode'] = _MODELSERVINGCLIENTRESPONSECODE
DESCRIPTOR.enum_types_by_name['ModelServingClientAction'] = _MODELSERVINGCLIENTACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelServingClientRequest = _reflection.GeneratedProtocolMessageType('ModelServingClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODELSERVINGCLIENTREQUEST,
  __module__ = 'model_serving_client_request_response_pb2'
  # @@protoc_insertion_point(class_scope:DeepLearningModelServer.ModelServingClientRequest)
  ))
_sym_db.RegisterMessage(ModelServingClientRequest)

ModelServingClientResponse = _reflection.GeneratedProtocolMessageType('ModelServingClientResponse', (_message.Message,), dict(
  DESCRIPTOR = _MODELSERVINGCLIENTRESPONSE,
  __module__ = 'model_serving_client_request_response_pb2'
  # @@protoc_insertion_point(class_scope:DeepLearningModelServer.ModelServingClientResponse)
  ))
_sym_db.RegisterMessage(ModelServingClientResponse)


# @@protoc_insertion_point(module_scope)
